### PR TITLE
return axios errors, trim() response body, skipContentTypeCheck

### PR DESCRIPTION
**Pull request by eviltik**

### CODE REVIEW

**Comment by eviltik** [comment]
see https://github.com/ndaidong/feed-reader/issues/38

**Comment by ndaidong** [comment]
@eviltik thank you, it cause some errors so the test does not pass. Let's I check it again.

**Comment by ndaidong** [comment]
@eviltik as I've seen, the test could not be passed because linter. You can fix by installing `standardjs` and using its `fix` command.

**Comment by ndaidong** [comment]
@eviltik I think that we should not change current behaviour, so I will try another idea to help you catch the error and debug.

**Comment by eviltik** [comment]
> @eviltik I think that we should not change current behaviour, so I will try another idea to help you catch the error and debug.

well, it's not really for debugging, i need to store all errors programmatically.

this PR include 3 things, sorry for that. Do you want i cleanup all and make 3 distinct PR using branches or is it ok ?

Btw, i've put skipContentCheck in axios options because i don't see another way to do that

**Comment by ndaidong** [comment]
@eviltik no problem, let's I clean up, this is the start for next version.

**Comment by eviltik** [comment]
> @eviltik no problem, let's I clean up, this is the start for next version.

Thank you !

Ha, i forgot to add something in the README regarding skipContentTypeCheck in options

**Pull request merged**
